"""adiciona tabela email

Revision ID: d50cd7556668
Revises: 102c13086aed
Create Date: 2025-11-28 14:45:10.993873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50cd7556668'
down_revision = '102c13086aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromEmail', sa.String(length=64), nullable=True),
    sa.Column('toEmail', sa.String(length=64), nullable=True),
    sa.Column('subjectEmail', sa.String(length=128), nullable=True),
    sa.Column('textEmail', sa.Text(), nullable=True),
    sa.Column('timestampEmail', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_timestampEmail'), ['timestampEmail'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_timestampEmail'))

    op.drop_table('emails')
    # ### end Alembic commands ###
